### ISSUE TITLE
potential bug about standalone vault installation with helm chart 

### ISSUE THREAD

**Issue by chuanran** [openlab-red/hashicorp-vault-for-openshift#34]
When I follow  this runbook for setting up a standalone vault using helm chart: https://github.com/openlab-red/hashicorp-vault-for-openshift/blob/master/vault/standalone/README.md, I encountered the following error:

```
# helm install standalone . -f override-standalone.yaml
coalesce.go:196: warning: cannot overwrite table with non table for openshift (map[enabled:false])
coalesce.go:196: warning: cannot overwrite table with non table for openshift (map[enabled:false])
coalesce.go:196: warning: cannot overwrite table with non table for openshift (map[enabled:false])
Error: template: vault/charts/consul/templates/server-statefulset.yaml:62:24: executing "vault/charts/consul/templates/server-statefulset.yaml" at <.Values.global.openshift.enabled>: can't evaluate field enabled in type interface {}
```
However, the above error seems does not make sense, because it reported error like ` <.Values.global.openshift.enabled>: can't evaluate field enabled in type interface {}`, but actually as following shows, in `templates/server-statefulset.yaml` file, there's only section `Values.global.openshift`, there's no such section like `Values.global.openshift.enabled`

```
      volumes:
        {{ template "vault.volumes" . }}
        - name: home
          emptyDir: {}
        {{- if .Values.global.openshift }}
        - name: {{ .Release.Name }}-vault-cert
          secret:
        {{- if ne .mode "ha" }}
            secretName: {{ .Release.Name }}-vault-cert
        {{- else }}
            secretName: {{ .Release.Name }}-vault-cert-active
        {{- end }}
            defaultMode: 420
        {{- end }}
```

I found a workaround is that for `override-standalone.yaml `, after I changed 

```
global:
  tlsDisable: false
  openshift: true
```
 To:

```
global:
  tlsDisable: false
  openshift:
    enabled: true
```

Then everything worked well, and I was able to create a standalone vault service. Could you evaluate here if it's a bug or anything I missed?  Thanks.

**Comment by radudd** [comment]
Thanks @chuanran for creating this issue and for the investigation. The problem is actually that the Vault Helm Charts were defining Consul as a dependency and both the warning you were seeing as well as the `.Values.global.openshift.enabled` variable were coming from Consul.
However, Consul is not required for a standalone installation, hence the dependency has been removed in [forked vault-helm repo ](https://github.com/radudd/vault-helm).
Now if you pull the latest changes from this repo you should be able to install the standalone version without any issues.

**Comment by chuanran** [comment]
thanks for the quick response and action, and glad this is resolved now!  @radudd , please feel free to close this issue. thanks.

**Comment by chuanran** [comment]
@radudd sorry, forgot to ask, consul dependency is definitely needed by HA deployment as you know, in that case, in https://github.com/openlab-red/hashicorp-vault-for-openshift/blob/master/vault/ha/README.md, for `override-ha.yaml`, do we need to make sure to change:
```
global:
  tlsDisable: false
  openshift: true
```
To:

```
global:
  tlsDisable: false
  openshift:
    enabled: true
```
if we don't do the change it would trigger similar error like `Error: template: vault/charts/consul/templates/server-statefulset.yaml:62:24: executing "vault/charts/consul/templates/server-statefulset.yaml" at <.Values.global.openshift.enabled>: can't evaluate field enabled in type interface {}
` right?  correct me if I understand wrongly.

**Comment by radudd** [comment]
Thanks for your comments @chuanran. Consul is only one of the options for storage backends when running Vault in HA mode, but indeed in our repo we are using it as an example to demonstrate Vault HA capabilities.
However, Consul needs to be installed, but can be as a separate chart, not necesarly as Helm dependency for Vault (how it was before configured in the forked repo providing the Helm chart and which was causing your initial issue). 
I assume that now for you it still doesn't work because you still have Consul as a Helm dependency in your working directory. You can try to delete the charts folder from the vault-helm directory and I guess all should be good after. Let me know if that helps. Cheers

Ps: `global.openshift.enabled` is a Consul Helm variable, whereas `global.openshift` is a Vault one.
